steps:
  # Set environment variables
  - name: 'bash'
    id: 'set-env'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Setting environment variables..."
        echo "BUILD_ID=$BUILD_ID"
        echo "COMMIT_SHA=$COMMIT_SHA"
        echo "BRANCH_NAME=$BRANCH_NAME"

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/chambers-api:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args: ['push', 'gcr.io/$PROJECT_ID/chambers-api:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chambers-api-staging'
      - '--image'
      - 'gcr.io/$PROJECT_ID/chambers-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/$PROJECT_ID/chambers-api:$COMMIT_SHA'

substitutions:
  _REGION: 'us-central1'

options:
  logging: CLOUD_LOGGING_ONLY
